server:
  port: 8084
spring:
  application:
    name: clientes
  profiles:
    active: local

---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/clientes
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none

